name: Publiser termbase

on:
  push:
    branches:
      - master
    paths:
      - termbase.yaml
      - skript/yaml_til_json.py

permissions:
  contents: write

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Sjekk ut repo
        uses: actions/checkout@v6

      - name: Sett opp Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Installer Python bibliotek
        run: |
          pip install pyyaml jsonschema

      - name: Generer JSON
        run: |
          python ./skript/yaml_til_json.py ./termbase.yaml ./termbase.json

      - name: Opprett GitHub-utgave
        id: release
        uses: softprops/action-gh-release@v3
        with:
          tag_name: latest
          target_commitish: ${{ github.sha }}
          name: termbase
          files: |
            termbase.yaml
            termbase.json
