name: Termtabell kvalitetskontroll

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  qc:
    runs-on: ubuntu-latest

    steps:
      - name: Hent kode
        uses: actions/checkout@v2

      - name: Sett opp Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Termtabell kvalitetskontroll
        run: bash ./skript/tester.sh
