name: Termtabell kvalitetskontroll

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Termtabell kvalitetskontroll
        run: bash ./skript/kjor_sjekker.sh
